config/routes.rb
Rails.application.routes.draw do
  
  get '/users/info', to: 'users#info'
  post '/users/charge', to: 'users#charge'
  get '/users/cancel_subscription', to: 'users#cancel_subscription'

  devise_for :users
  root to: 'home#index'

  resources :publications, only: [:index, :show]
  authenticated :user do
    root to: 'publications#index', as: :authenticated_root
  end

  namespace :admin do
    resources :publications
  end

end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :subscription

  after_create :create_subscription

  def create_subscription
    Subscription.create(user_id: id) if subscription.nil?
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController
  before_action :find_publication, only: [:show, :edit, :update, :destroy]

  def index
    @publications = Publication.order("created_at DESC")
  end

  def show 
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)
    if @publication.save
      redirect_to admin_publication_path(@publication), alert: "Publication Created"
    else
      render :new, alert: "Something went wrong"
    end
  end

  def edit
  end

  def update
    if @publication.update(publication_params)
      redirect_to admin_publication_path(@publication), alert: "Publication Updated"
    else
      render :edit, alert: "Something went wrong"
    end
  end

  def destroy
    @publication.destroy
    redirect_to admin_publications_path, alert: "Publication Destroyed"
  end

  private
  def find_publication
    @publication = Publication.find(params[:id])
  end
  def publication_params
    params.require(:publication).permit(:title, :description, :file_url)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_for_admin

  def check_for_admin
    if current_user.nil? || !current_user.is_admin?
      redirect_to root_path, alert: "You must be an admin to access this."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :check_for_subscription, only: :show

  def index
    @publications = Publication.order "created_at DESC"
  end

  def show
    @publication = Publication.find params[:id]
  end

  def check_for_subscription
    unless current_user.subscription.active
      redirect_to publications_path, alert: "You must be subscribed."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def info
    @subscription = current_user.subscription
    if @subscription.active
      @stripe_customer = Stripe::Customer.retrieve(@subscription.stripe_user_id)
      @stripe_subscription = @stripe_customer.subscriptions.first
    end
  end

  def cancel_subscription
    @stripe_customer = Stripe::Customer.retrieve(
      current_user.subscription.stripe_user_id
    )
    @stripe_subscription = @stripe_customer.subscriptions.first

    @stripe_subscription.delete
    current_user.subscription.active = false
    current_user.subscription.save
    redirect_to users_info_path, alert: "Subscription Cancelled"
  end

  def charge
    token = params['stripeToken']
    customer = Stripe::Customer.create(
      source: token,
      plan: 'mysubscriptionlevel1',
      email: current_user.email
    )

    current_user.subscription.stripe_user_id = customer.id
    current_user.subscription.active = true
    current_user.subscription.save
    redirect_to users_info_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/publications/_form.html.haml
= form_for ["admin", @publication] do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :file_url, "File URL"
    = f.text_field :file_url, class: "form-control"

  .form-group
    = f.submit label, class: "btn btn-primary"

app/views/admin/publications/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3 Edit #{@publication.title}

    = render 'form', label: "Update Publication"

app/views/admin/publications/index.html.haml
%h2 Publications Admin

%p
  = link_to "New Publication", new_admin_publication_path, class: "btn btn-primary"

- @publications.each do |publication|
  .panel.panel-default
    .panel-heading
      %h2.panel-title= publication.title
    .panel-body
      %p= publication.description
      %p= publication.file_url
    .panel-footer
      = link_to "View more details", admin_publication_path(publication), class: "btn btn-default"
      = link_to "Edit", edit_admin_publication_path(publication), class: "btn btn-default"

app/views/admin/publications/new.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3 New Publication

    = render 'form', label: "Create Publication"

app/views/admin/publications/show.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title= @publication.title
  .panel-body
    %p= @publication.description
    %p= @publication.file_url
  .panel-footer
    = link_to "Back", admin_publications_path

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><strong>SB</strong></a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.email}", users_info_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Admin", admin_publications_path %></li>

          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
          <li><%= link_to "Publications", publications_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/home/index.html.haml
%h1 Hello World

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubscriptionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'application/nav' %>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/publications/index.html.haml
%h2 Publications

- @publications.each do |publication|
  .panel.panel-default
    .panel-heading
      %h2.panel-title= publication.title
    .panel-body
      %p= publication.description
      %p= publication.file_url
    .panel-footer
      = link_to "View more details", publication, class: "btn btn-default"

app/views/publications/show.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title= @publication.title
  .panel-body
    %p= @publication.description
    %p= @publication.file_url
  .panel-footer
    = link_to "Back", publications_path

app/views/users/_form.html.erb
<h4>Begin your $9.99 a month subscription</h4>
<form action="/users/charge" method="POST" id="payment-form">
  <p class="alert alert-danger" style="display: none;" id="error">
    <span class="payment-errors"></span>
  </p>

  <div class="row">
    <div class="col-md-6">
      <label>Card Number</label>
      <input class="form-control" type="text" size="20" data-stripe="number" placeholder="4242424242424242"/>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>CVC</label>
      <input type="text" data-stripe="cvc" class="form-control" placeholder="123">
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>Expiration</label>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1">
      <label>MM</label>
      <input type="text" data-stripe="exp-month" class="form-control" placeholder="01">
    </div>
    <div class="col-xs-1">
      <label>YYYY</label>
      <input type="text" data-stripe="exp-year" class="form-control" placeholder="2020">
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3">
      <br/><button class="btn btn-primary" type="submit">Create Subscription</button>
    </div>
  </div>

  <%= token_tag nil %>
</form>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_RrmWYjH35uiD7zDab5QpOcwQ');

  function stripeResponseHandler(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $form.find("#error").fadeIn();
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
    } else {
      // response contains id and card, which contains additional card details
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and submit
      $form.get(0).submit();
    }
  };

  jQuery(function($) {
    $('#payment-form').submit(function(event) {
      var $form = $(this);
      $form.find("#error").hide();

      // Disable the submit button to prevent repeated clicks
      $form.find('button').prop('disabled', true);

      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from submitting with the default action
      return false;
    });
  });
</script>

app/views/users/info.html.haml
.container
  %h3 Account for #{current_user.email}
  %p= link_to "Edit Account", edit_user_registration_path
  %hr/
  - if @subscription.active
    %h3
      Current plan renews at:
      = Time.at(@stripe_subscription['current_period_end']).strftime("%D")

    %p= link_to "Cancel Subscription", users_cancel_subscription_path, class: "btn btn-danger"
  - else
    = render 'form'